service: pokeapi-lambda

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    inMemory: true
    port: 8000
    migrate: true
    onStart: true

provider:
  name: aws
  runtime: nodejs22.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  # profile: ${aws:profile, 'default'}

functions:
  getPokemonByName:
    handler: src/features/pokemon/infraestructure/lambda/handlers/getPokemonByName.getPokemonByName
    role: getPokemonByNameIamRole
    environment:
      POKEMON_TABLE_NAME: ${self:service}-${self:provider.stage}-searchedPokemonsTable
      MANAGE_POKEMONS_LAMBDA: ${self:service}-${self:provider.stage}-managePokemons

    events:
      - httpApi:
          method: GET
          path: /pokemons/{pokemonName}

  managePokemons:
    handler: src/features/pokemon/infraestructure/lambda/handlers/managePokemons.managePokemons
    role: managePokemonsIamRole
    environment:
      POKEAPI_BASE_URL: https://pokeapi.co/api/v2
      POKEMON_TABLE_NAME: ${self:service}-${self:provider.stage}-searchedPokemonsTable
    events:
      - httpApi:
          method: POST
          path: /pokemons/{pokemonName}

resources:
  Resources:
    searchedPokemonsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-searchedPokemonsTable
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    getPokemonByNameIamRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${self:provider.stage}-getPokemonByName-iamRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: InvokeLambdaPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource:
                    - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-${self:provider.stage}-managePokemons'

          - PolicyName: DynamoDBAccessPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:GetItem
                  Resource: !GetAtt searchedPokemonsTable.Arn

          - PolicyName: CloudWatchLogsAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: '*'

    managePokemonsIamRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${self:provider.stage}-managePokemons-iamRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: DynamoDBAccessPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                  Resource: !GetAtt searchedPokemonsTable.Arn

          - PolicyName: CloudWatchLogsAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: '*'
